openapi: 3.2.0
info:
  title: Trip.com integreated Api v1.0 Reservation API
  version: '1.0'
security:
- Bearer: []
  ClientId: []
  Currency: []
  Language: []
tags:
- name: Reservation
paths:
  /api/v1:
    post:
      tags:
      - Reservation
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/JObjectTripComRequestDto'
          application/json:
            schema:
              $ref: '#/components/schemas/JObjectTripComRequestDto'
          text/json:
            schema:
              $ref: '#/components/schemas/JObjectTripComRequestDto'
          application/*+json:
            schema:
              $ref: '#/components/schemas/JObjectTripComRequestDto'
      responses:
        '200':
          description: OK
      summary: Create api
      x-summary-source: derived
      operationId: postApiV1
      x-operation-id-source: derived
components:
  schemas:
    JToken:
      type: array
      items:
        $ref: '#/components/schemas/JToken'
    ServiceNameEnum:
      enum:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      type: integer
      format: int32
    TripComRequestHeader:
      required:
      - accountId
      - requestTime
      - serviceName
      - sign
      - version
      type: object
      properties:
        accountId:
          minLength: 1
          type: string
        serviceName:
          $ref: '#/components/schemas/ServiceNameEnum'
        requestTime:
          minLength: 1
          type: string
        version:
          minLength: 1
          type: string
        sign:
          minLength: 1
          type: string
      additionalProperties: false
    JObjectTripComRequestDto:
      type: object
      properties:
        header:
          $ref: '#/components/schemas/TripComRequestHeader'
        body:
          type:
          - object
          - 'null'
          additionalProperties:
            $ref: '#/components/schemas/JToken'
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: http
      scheme: Bearer
      bearerFormat: JWT
    ClientId:
      type: apiKey
      name: ClientId
      in: header
    Currency:
      type: apiKey
      name: Currency
      in: header
    Language:
      type: apiKey
      name: Language
      in: header
